# Generated by Django 5.1.3 on 2025-01-04 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='admins',
            field=models.ManyToManyField(related_name='user_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='server',
            name='moderators',
            field=models.ManyToManyField(related_name='user_moderators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='members',
            field=models.ManyToManyField(related_name='user_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
